### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by sidram01** [snood1205/camera-angulara#2]
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (R:\testserve\camera-angulara-staging\camera-angulara-staging\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (R:\testserve\camera-angulara-staging\camera-angulara-staging\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

any fixes for this ?

**Comment by snood1205** [comment]
Hey, I'm so sorry I've been very busy lately with my day-job. I'll try to get to this either tonight or over the weekend. Thanks for using the repo!

**Comment by sidram01** [comment]
hey its okay.. im an intern working on a project .came accross ur code..
was trying to run it

**Comment by sidram01** [comment]
Hai, Eli is ther any way to

**Comment by sidram01** [comment]
Hey Eli ,
 Is ther any way to stop the stream of video camera ?
